apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: <base64-encoded-git-username>
  GITSYNC_PASSWORD: <base64-encoded-git-token>
  GIT_SYNC_USERNAME: <base64-encoded-git-username>
  GIT_SYNC_PASSWORD: <base64-encoded-git-token>
